const expertQuestions = [
  /* =======================
          rank1（準1級レベル）
         ======================= */
  {
    level: "expert",
    rank: "1",
    kanji: "杣人",
    reading: "そまびと",
    meaning: "山で木を切り出すことを仕事とする人",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "躊躇",
    reading: "ちゅうちょ",
    meaning: "決心がつかず、ためらうこと",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "汎用",
    reading: "はんよう",
    meaning: "広い目的に使えること",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "膠着",
    reading: "こうちゃく",
    meaning: "物事が行き詰まり、動かなくなること",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "逡巡",
    reading: "しゅんじゅん",
    meaning: "決断できずに迷い、ためらうこと",
  },

  {
    level: "expert",
    rank: "1",
    kanji: "峻厳",
    reading: "しゅんげん",
    meaning: "態度や規律が非常に厳しいこと",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "詭計",
    reading: "きけい",
    meaning: "人をだますためのずるい計略",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "緻密",
    reading: "ちみつ",
    meaning: "細かいところまで行き届いていること",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "敢行",
    reading: "かんこう",
    meaning: "困難を承知で思い切って行うこと",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "彷徨",
    reading: "ほうこう、さまよう",
    meaning: "目的なく歩き回る、または迷うこと",
  },

  {
    level: "expert",
    rank: "1",
    kanji: "稟性",
    reading: "ひんせい",
    meaning: "生まれつき備わっている性質",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "弛緩",
    reading: "しかん",
    meaning: "緊張がゆるんでだらけること",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "慫慂",
    reading: "しょうよう",
    meaning: "人に強くすすめて行動を促すこと",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "艱え",
    reading: "なやましげ",
    meaning: "苦しくつらく、悩みが多いこと",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "厳粛",
    reading: "げんしゅく",
    meaning: "非常に厳かで引き締まっていること",
  },

  {
    level: "expert",
    rank: "1",
    kanji: "彙報",
    reading: "いほう",
    meaning: "情報や報告をまとめて伝えること",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "饗応",
    reading: "きょうおう",
    meaning: "客をもてなして食事などを出すこと",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "稀覯書",
    reading: "きこうしょ",
    meaning: "数が少なく、手に入りにくい貴重な書物",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "遡行",
    reading: "そこう",
    meaning: "川の流れに逆らって進むこと",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "俯瞰",
    reading: "ふかん",
    meaning: "高い位置から全体を見下ろすこと",
  },

  {
    level: "expert",
    rank: "1",
    kanji: "暫時",
    reading: "ざんじ",
    meaning: "しばらくの間、短い時間",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "頑迷",
    reading: "がんめい",
    meaning: "自分の考えに固執して聞き入れないこと",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "幽棲",
    reading: "ゆうせい",
    meaning: "人里離れた場所でひっそりと暮らすこと",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "焦眉",
    reading: "しょうび",
    meaning: "非常に差し迫っていること",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "喚起",
    reading: "かんき",
    meaning: "注意や関心を呼び起こすこと",
  },

  {
    level: "expert",
    rank: "1",
    kanji: "稠密",
    reading: "ちゅうみつ",
    meaning: "物事が非常に細かく、すき間なく詰まっていること",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "潜藪",
    reading: "せんそう",
    meaning: "人目を避けてひそかに隠れ住むこと",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "謹厳実直",
    reading: "きんげんじっちょく",
    meaning: "態度が慎み深く、非常に真面目で正直なこと",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "逼塞",
    reading: "ひっそく",
    meaning: "世間から離れて引きこもり、活動しないこと",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "峨峨",
    reading: "がが",
    meaning: "山などが高く険しくそびえ立つさま",
  },

  {
    level: "expert",
    rank: "1",
    kanji: "偏頗",
    reading: "へんぱ",
    meaning: "考え方や扱いが一方にかたよって公平でないこと",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "巽",
    reading: "たつみ",
    meaning: "方角の一つで、南東を指す",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "隘路",
    reading: "あいろ",
    meaning: "道幅が狭く、通行しにくい道",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "釣果",
    reading: "ちょうか",
    meaning: "釣りで得られた魚の成果",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "偉丈夫",
    reading: "いじょうふ",
    meaning: "体が大きく、気力や器量にすぐれた男",
  },

  {
    level: "expert",
    rank: "1",
    kanji: "醇朴",
    reading: "じゅんぼく",
    meaning: "心が純粋で飾り気がなく素直なこと",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "謁見",
    reading: "えっけん",
    meaning: "身分の高い人に直接会うこと",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "猥雑",
    reading: "わいざつ",
    meaning: "品がなく、乱れていて下品なこと",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "衒気",
    reading: "げんき",
    meaning: "自分の才能や知識を誇示しようとする気持ち",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "夙昔",
    reading: "しゅくせき",
    meaning: "ずっと昔、古い時代",
  },

  {
    level: "expert",
    rank: "1",
    kanji: "瑣末",
    reading: "さまつ",
    meaning: "取るに足らないほど細かく重要でないこと",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "据置",
    reading: "すえおき",
    meaning: "変更せず、そのままの状態にしておくこと",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "楚々",
    reading: "そそ",
    meaning: "姿や様子が清らかで上品なさま",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "膏肓",
    reading: "こうこう",
    meaning: "病気や欠点が深く入り込み、治らない状態",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "毀誉",
    reading: "きよ",
    meaning: "悪く言うことと、ほめること",
  },

  {
    level: "expert",
    rank: "1",
    kanji: "逼迫度",
    reading: "ひっぱくど",
    meaning: "物事がどれほど差し迫っているかの度合い",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "幽邃",
    reading: "ゆうすい",
    meaning: "奥深く静かで、神秘的な趣があること",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "慇懃無礼",
    reading: "いんぎんぶれい",
    meaning: "表面上は丁寧だが、内心では失礼な態度",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "高踏的",
    reading: "こうとうてき",
    meaning: "理想や考えが高尚すぎて現実離れしていること",
  },
  {
    level: "expert",
    rank: "1",
    kanji: "泥中の蓮",
    reading: "でいちゅうのはす",
    meaning: "悪い環境の中でも清らかさを失わない人や物事のたとえ",
  },

  /* =======================
          rank2（準1級〜1級）
         ======================= */
  {
    level: "expert",
    rank: "2",
    kanji: "佶屈",
    reading: "きっくつ",
    meaning: "文章や言い回しがかたく、なめらかでなくぎこちないこと",
  },
  {
    level: "expert",
    rank: "2",
    kanji: "嫋やか",
    reading: "たおやか",
    meaning: "姿や動きがしなやかで、上品でやさしいさま",
  },
  {
    level: "expert",
    rank: "2",
    kanji: "瀟洒",
    reading: "しょうしゃ",
    meaning: "あか抜けていて上品で、さっぱりと洗練されていること",
  },
  {
    level: "expert",
    rank: "2",
    kanji: "靉靆",
    reading: "あいたい",
    meaning: "雲やもやがたなびいて、ぼんやりとかすむさま",
  },
  {
    level: "expert",
    rank: "2",
    kanji: "蹉跌",
    reading: "さてつ",
    meaning: "つまずき。失敗や挫折のこと",
  },

  {
    level: "expert",
    rank: "2",
    kanji: "冗漫",
    reading: "じょうまん",
    meaning: "文章や話がむだに長く、要点がはっきりしないこと",
  },
  {
    level: "expert",
    rank: "2",
    kanji: "鯑",
    reading: "かずのこ",
    meaning: "ニシンの卵を塩漬けにした食品（数の子）",
  },
  {
    level: "expert",
    rank: "2",
    kanji: "瑣事",
    reading: "さじ",
    meaning: "こまごまして取るに足りない事柄",
  },
  {
    level: "expert",
    rank: "2",
    kanji: "濠",
    reading: "ほり",
    meaning: "城や陣地の周りに掘って水を入れたりする溝（堀）",
  },
  {
    level: "expert",
    rank: "2",
    kanji: "曖冥",
    reading: "あいめい",
    meaning: "はっきりせず、ぼんやり暗いこと。あいまいで不明なこと",
  },

  {
    level: "expert",
    rank: "2",
    kanji: "錯簡",
    reading: "さっかん",
    meaning: "書物の簡（札）が入れ違って順序が乱れること。転じて文章の錯乱",
  },
  {
    level: "expert",
    rank: "2",
    kanji: "饕餮",
    reading: "とうてつ",
    meaning: "むさぼり食うこと。非常に貪欲なさま（またはその怪物の名）",
  },
  {
    level: "expert",
    rank: "2",
    kanji: "穹窿",
    reading: "きゅうりゅう",
    meaning: "丸く高く盛り上がった形。天の丸いドーム状の形",
  },
  {
    level: "expert",
    rank: "2",
    kanji: "冰解",
    reading: "ひょうかい",
    meaning: "氷が解けるように、わだかまりや疑いがすっきり解けること",
  },
  {
    level: "expert",
    rank: "2",
    kanji: "罅",
    reading: "ひび",
    meaning: "物の表面にできる割れ目。ひび割れ",
  },

  {
    level: "expert",
    rank: "2",
    kanji: "麤",
    reading: "あらい",
    meaning: "きめが細かくなく、ざらついていること。大ざっぱなさま",
  },
  {
    level: "expert",
    rank: "2",
    kanji: "纛",
    reading: "はたぼこ",
    meaning: "軍陣で大将の位置を示す大きな旗印（長い柄の旗）",
  },
  {
    level: "expert",
    rank: "2",
    kanji: "戛然",
    reading: "かつぜん",
    meaning: "急に音がするさま。かちっと途切れるように止むさま",
  },
  {
    level: "expert",
    rank: "2",
    kanji: "悒鬱",
    reading: "ゆううつ",
    meaning: "気分がふさぎ込み、晴れないこと",
  },
  {
    level: "expert",
    rank: "2",
    kanji: "椹",
    reading: "さわら",
    meaning: "ヒノキ科の常緑高木の名（材は建築・器具などに用いる）",
  },

  {
    level: "expert",
    rank: "2",
    kanji: "寂寥",
    reading: "せきりょう",
    meaning: "ひっそりとしてもの寂しいこと。さびしく広がるさま",
  },
  {
    level: "expert",
    rank: "2",
    kanji: "閘門",
    reading: "こうもん",
    meaning: "運河で水位差を調整し、船を通すための水門（ロック・ゲート）",
  },
  {
    level: "expert",
    rank: "2",
    kanji: "欝憤",
    reading: "うっぷん",
    meaning: "心の中にたまって晴れない怒りや不満",
  },
  {
    level: "expert",
    rank: "2",
    kanji: "狡猾",
    reading: "こうかつ",
    meaning: "ずるがしこく、たくみにだますさま",
  },
  {
    level: "expert",
    rank: "2",
    kanji: "殞命",
    reading: "いんめい",
    meaning: "命を落とすこと。戦死・落命すること",
  },

  {
    level: "expert",
    rank: "2",
    kanji: "矮躯",
    reading: "わいく",
    meaning: "背丈が低い体つき。小柄な身体",
  },
  {
    level: "expert",
    rank: "2",
    kanji: "嚢中",
    reading: "のうちゅう",
    meaning: "袋の中。転じて、すでに自分の思い通りにできる状態（嚢中の物）",
  },
  {
    level: "expert",
    rank: "2",
    kanji: "鬻ぐ",
    reading: "ひさぐ",
    meaning: "品物を売る。金銭のために自分の物や能力を提供する",
  },
  {
    level: "expert",
    rank: "2",
    kanji: "慴伏",
    reading: "しょうふく",
    meaning: "おそれてひれ伏し、逆らわずに従うこと",
  },
  {
    level: "expert",
    rank: "2",
    kanji: "辮髪",
    reading: "べんぱつ",
    meaning: "髪を編んでひも状に垂らした髪形（清朝時代の中国など）",
  },

  {
    level: "expert",
    rank: "2",
    kanji: "靡く",
    reading: "なびく",
    meaning: "風などに従って揺れ動くこと。転じて、考えや勢力に従うこと",
  },
  {
    level: "expert",
    rank: "2",
    kanji: "蓊鬱",
    reading: "おううつ",
    meaning: "草木が生い茂って暗いほどにこんもりしているさま",
  },
  {
    level: "expert",
    rank: "2",
    kanji: "溌剌",
    reading: "はつらつ",
    meaning: "生き生きとして元気に満ちあふれているさま",
  },
  {
    level: "expert",
    rank: "2",
    kanji: "邂逅",
    reading: "かいこう",
    meaning: "思いがけなく出会うこと。偶然のめぐりあい",
  },
  {
    level: "expert",
    rank: "2",
    kanji: "彳亍",
    reading: "てきちょく",
    meaning: "少し進んでは立ち止まること。ためらって進まないさま",
  },

  {
    level: "expert",
    rank: "2",
    kanji: "醴",
    reading: "あまざけ",
    meaning: "米を発酵させて作る甘い飲み物。古くは甘味のある酒全般",
  },
  {
    level: "expert",
    rank: "2",
    kanji: "皺",
    reading: "しわ",
    meaning: "皮膚や布などにできる細かな折れ目",
  },
  {
    level: "expert",
    rank: "2",
    kanji: "饑饉",
    reading: "ききん",
    meaning: "作物がとれず、食料が不足して多くの人が飢えること",
  },
  {
    level: "expert",
    rank: "2",
    kanji: "腆顔",
    reading: "てんがん",
    meaning: "厚かましく、恥じる様子のない顔つき",
  },
  {
    level: "expert",
    rank: "2",
    kanji: "悼詞",
    reading: "とうし",
    meaning: "亡くなった人を悼み、その死を惜しんで述べる言葉",
  },

  /* =======================
          rank3（漢検1級：超難読）
         ======================= */
  {
    level: "expert",
    rank: "3",
    kanji: "躑躅",
    reading: "つつじ",
    meaning: "春から初夏にかけて咲く花木の一種。赤や白などの花をつける",
  },
  {
    level: "expert",
    rank: "3",
    kanji: "鷦鷯",
    reading: "みそさざい",
    meaning: "非常に小型で、さえずりの美しい鳥",
  },
  {
    level: "expert",
    rank: "3",
    kanji: "蝌蚪",
    reading: "おたまじゃくし",
    meaning: "カエルなどの両生類の幼生",
  },
  {
    level: "expert",
    rank: "3",
    kanji: "蜉蝣",
    reading: "かげろう",
    meaning: "寿命が非常に短い昆虫。転じて、はかないもののたとえ",
  },
  {
    level: "expert",
    rank: "3",
    kanji: "鸞鳳",
    reading: "らんぽう",
    meaning: "想像上の瑞鳥。めでたい出来事の象徴",
  },

  {
    level: "expert",
    rank: "3",
    kanji: "鱟",
    reading: "かぶとがに",
    meaning: "硬い甲羅を持つ海生動物。生きた化石とされる",
  },
  {
    level: "expert",
    rank: "3",
    kanji: "鰤",
    reading: "ぶり",
    meaning: "成長によって名前が変わる出世魚の一種",
  },
  {
    level: "expert",
    rank: "3",
    kanji: "鷽",
    reading: "うそ",
    meaning: "スズメ目の小鳥。名前が「嘘」に通じることでも知られる",
  },
  {
    level: "expert",
    rank: "3",
    kanji: "螽斯",
    reading: "きりぎりす",
    meaning: "秋に鳴く昆虫の一種",
  },
  {
    level: "expert",
    rank: "3",
    kanji: "匏瓜",
    reading: "ほう",
    meaning: "ひょうたんの実。転じて役に立たないもののたとえ",
  },

  {
    level: "expert",
    rank: "3",
    kanji: "罌粟",
    reading: "けし",
    meaning: "赤や白の花を咲かせる植物。麻薬の原料としても知られる",
  },
  {
    level: "expert",
    rank: "3",
    kanji: "黔首",
    reading: "けんしゅ",
    meaning: "古代中国で、一般民衆を指した言葉",
  },
  {
    level: "expert",
    rank: "3",
    kanji: "糴",
    reading: "かいよね",
    meaning: "米を買い集めること",
  },
  {
    level: "expert",
    rank: "3",
    kanji: "貘",
    reading: "ばく",
    meaning: "夢を食べるとされる想像上の動物。または実在のバク",
  },
  {
    level: "expert",
    rank: "3",
    kanji: "鶸",
    reading: "ひわ",
    meaning: "小型の鳥で、黄色がかった羽をもつ",
  },

  {
    level: "expert",
    rank: "3",
    kanji: "鯢",
    reading: "さんしょううお",
    meaning: "山間の清流に生息する両生類",
  },
  {
    level: "expert",
    rank: "3",
    kanji: "膾",
    reading: "なます",
    meaning: "魚や肉を細切りにして調味した料理",
  },
  {
    level: "expert",
    rank: "3",
    kanji: "讌",
    reading: "うたげ",
    meaning: "酒や食事をともにして楽しむ宴会",
  },
  {
    level: "expert",
    rank: "3",
    kanji: "黯然",
    reading: "あんぜん",
    meaning: "気落ちして暗い表情をしているさま",
  },
  {
    level: "expert",
    rank: "3",
    kanji: "瓢鮎図",
    reading: "ひょうねんず",
    meaning: "禅の公案を題材にした水墨画の画題",
  },

  {
    level: "expert",
    rank: "3",
    kanji: "鼯鼠",
    reading: "むささび",
    meaning: "木から木へ滑空する哺乳類",
  },
  {
    level: "expert",
    rank: "3",
    kanji: "鬣",
    reading: "たてがみ",
    meaning: "馬やライオンの首元に生える長い毛",
  },
  {
    level: "expert",
    rank: "3",
    kanji: "鱗雲",
    reading: "うろこぐも",
    meaning: "魚の鱗のように見える雲（巻積雲）",
  },
  {
    level: "expert",
    rank: "3",
    kanji: "倏忽",
    reading: "しゅっこつ",
    meaning: "きわめて短い時間。瞬く間",
  },
  {
    level: "expert",
    rank: "3",
    kanji: "驢馬",
    reading: "ろば",
    meaning: "ウマ科の動物。荷物運搬に使われる",
  },

  {
    level: "expert",
    rank: "3",
    kanji: "牝牡",
    reading: "めすおす",
    meaning: "雌と雄。女性と男性の別",
  },
  {
    level: "expert",
    rank: "3",
    kanji: "蟠る",
    reading: "わだかまる",
    meaning: "心の中に不満や疑念が残って解消しないこと",
  },
  {
    level: "expert",
    rank: "3",
    kanji: "鷭",
    reading: "ばん",
    meaning: "水辺に生息する鳥の一種",
  },
  {
    level: "expert",
    rank: "3",
    kanji: "鷸",
    reading: "しぎ",
    meaning: "湿地や干潟にすむ鳥の総称",
  },
  {
    level: "expert",
    rank: "3",
    kanji: "鱚",
    reading: "きす",
    meaning: "白身で淡泊な味の魚",
  },

  {
    level: "expert",
    rank: "3",
    kanji: "蚰蜒",
    reading: "げじげじ",
    meaning: "細長い体と多数の脚をもつ節足動物",
  },
  {
    level: "expert",
    rank: "3",
    kanji: "饕餮図",
    reading: "とうてつず",
    meaning: "古代中国の怪獣文様を描いた図",
  },
  {
    level: "expert",
    rank: "3",
    kanji: "黥刑",
    reading: "げいけい",
    meaning: "罪人の顔や体に入れ墨を施す刑罰",
  },
  {
    level: "expert",
    rank: "3",
    kanji: "贔屓",
    reading: "ひいき",
    meaning: "特定の人や物を特別に目をかけること",
  },
  {
    level: "expert",
    rank: "3",
    kanji: "鏖殺",
    reading: "おうさつ",
    meaning: "一人残らず殺すこと。皆殺し",
  },

  /* =======================
          BOSS（1級上位：激ムズ）
         ======================= */
  {
    level: "expert",
    rank: "BOSS",
    kanji: "靉霧",
    reading: "あいむ",
    meaning: "もやや霧が立ちこめて、はっきり見えないさま",
  },
  {
    level: "expert",
    rank: "BOSS",
    kanji: "驃騎",
    reading: "ひょうき",
    meaning: "勇敢で機動力のある騎兵",
  },
  {
    level: "expert",
    rank: "BOSS",
    kanji: "鸚鵡",
    reading: "おうむ",
    meaning: "人の言葉をまねて鳴くことで知られる鳥",
  },
  {
    level: "expert",
    rank: "BOSS",
    kanji: "讖言",
    reading: "しんげん",
    meaning: "未来を予言する言葉",
  },
  {
    level: "expert",
    rank: "BOSS",
    kanji: "颶風",
    reading: "ぐふう",
    meaning: "激しく吹く暴風。台風のこと",
  },

  {
    level: "expert",
    rank: "BOSS",
    kanji: "樒",
    reading: "しきみ",
    meaning: "仏事に使われる常緑樹",
  },
  {
    level: "expert",
    rank: "BOSS",
    kanji: "黠い",
    reading: "かしこい",
    meaning: "ずる賢く抜け目がないさま",
  },
  {
    level: "expert",
    rank: "BOSS",
    kanji: "嬋娟",
    reading: "せんけん",
    meaning: "姿が美しく、しなやかなさま",
  },
  {
    level: "expert",
    rank: "BOSS",
    kanji: "饕餮神",
    reading: "とうてつしん",
    meaning: "貪欲さを象徴する想像上の神",
  },
  {
    level: "expert",
    rank: "BOSS",
    kanji: "驢鳴犬吠",
    reading: "ろめいけんばい",
    meaning: "価値のない議論や文章のたとえ",
  },

  {
    level: "expert",
    rank: "BOSS",
    kanji: "巫覡",
    reading: "ふげき",
    meaning: "神の意志を人に伝える巫女や神職",
  },
  {
    level: "expert",
    rank: "BOSS",
    kanji: "魃魈",
    reading: "ばつしょう",
    meaning: "人に害をなすとされる妖怪",
  },
  {
    level: "expert",
    rank: "BOSS",
    kanji: "鯤鯨",
    reading: "こんげい",
    meaning: "巨大な魚や鯨のたとえ",
  },
  {
    level: "expert",
    rank: "BOSS",
    kanji: "颯然",
    reading: "さつぜん",
    meaning: "風のようにすばやく現れるさま",
  },
  {
    level: "expert",
    rank: "BOSS",
    kanji: "鐙",
    reading: "あぶみ",
    meaning: "馬に乗るとき足をかける道具",
  },

  {
    level: "expert",
    rank: "BOSS",
    kanji: "麝香",
    reading: "じゃこう",
    meaning: "動物から得られる強い香りの香料",
  },
  {
    level: "expert",
    rank: "BOSS",
    kanji: "酖毒",
    reading: "たんどく",
    meaning: "酒や毒によって害すること",
  },
  {
    level: "expert",
    rank: "BOSS",
    kanji: "懿徳",
    reading: "いとく",
    meaning: "すぐれて気高い徳",
  },
  {
    level: "expert",
    rank: "BOSS",
    kanji: "讐敵",
    reading: "しゅうてき",
    meaning: "深い恨みをもつ敵",
  },

  {
    level: "expert",
    rank: "BOSS",
    kanji: "櫛比",
    reading: "しっぴ",
    meaning: "櫛の歯のようにすき間なく並ぶこと",
  },
  {
    level: "expert",
    rank: "BOSS",
    kanji: "巌嶺",
    reading: "がんれい",
    meaning: "切り立った険しい山の峰",
  },
  {
    level: "expert",
    rank: "BOSS",
    kanji: "磊落",
    reading: "らいらく",
    meaning: "小事にこだわらず、心が大きいさま",
  },
  {
    level: "expert",
    rank: "BOSS",
    kanji: "鱗介",
    reading: "りんかい",
    meaning: "魚類や水生生物の総称",
  },
  {
    level: "expert",
    rank: "BOSS",
    kanji: "鱷魚",
    reading: "がくぎょ",
    meaning: "ワニのこと",
  },

  {
    level: "expert",
    rank: "BOSS",
    kanji: "赧然",
    reading: "たんぜん",
    meaning: "恥じて顔を赤らめるさま",
  },
  {
    level: "expert",
    rank: "BOSS",
    kanji: "瞑目",
    reading: "めいもく",
    meaning: "目を閉じること。転じて死去すること",
  },
  {
    level: "expert",
    rank: "BOSS",
    kanji: "黠智",
    reading: "かつち",
    meaning: "ずる賢く働く知恵",
  },
  {
    level: "expert",
    rank: "BOSS",
    kanji: "饗宴",
    reading: "きょうえん",
    meaning: "盛大にもてなす宴会",
  },
  {
    level: "expert",
    rank: "BOSS",
    kanji: "巫術",
    reading: "ふじゅつ",
    meaning: "神秘的な力を用いる術",
  },

  {
    level: "expert",
    rank: "BOSS",
    kanji: "驃勇",
    reading: "ひょうゆう",
    meaning: "勇ましくすばやいこと",
  },
  {
    level: "expert",
    rank: "BOSS",
    kanji: "瀰漫",
    reading: "びまん",
    meaning: "広い範囲に行き渡ること",
  },
];

export default expertQuestions;
