const hardQuestions = [
  /* =======================
          rank1（上級の入り口）
         ======================= */
  {
    level: "hard",
    rank: "1",
    kanji: "希薄",
    reading: "きはく",
    meaning: "内容や程度がうすく、十分でないこと",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "抵抗",
    reading: "ていこう",
    meaning: "外からの力や働きに逆らうこと",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "最適化",
    reading: "さいてきか",
    meaning: "最もよい状態になるように調整すること",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "精密",
    reading: "せいみつ",
    meaning: "非常に細かく正確であること",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "抽出",
    reading: "ちゅうしゅつ",
    meaning: "必要なものだけを選び出すこと",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "均衡",
    reading: "きんこう",
    meaning: "全体がつり合いのとれた状態",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "錯覚",
    reading: "さっかく",
    meaning: "事実とは異なって思い違いをすること",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "把握",
    reading: "はあく",
    meaning: "全体の様子をしっかり理解すること",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "概算",
    reading: "がいさん",
    meaning: "おおよその見積もりを出すこと",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "堅固",
    reading: "けんご",
    meaning: "非常にかたく、壊れにくいこと",
  },

  {
    level: "hard",
    rank: "1",
    kanji: "促進",
    reading: "そくしん",
    meaning: "物事の進行を早めること",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "潜在",
    reading: "せんざい",
    meaning: "表には現れていないが内にひそんでいること",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "緩和",
    reading: "かんわ",
    meaning: "きびしさや緊張をやわらげること",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "均質",
    reading: "きんしつ",
    meaning: "性質や状態が全体にわたって同じであること",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "継承",
    reading: "けいしょう",
    meaning: "前のものを受け継いで引き続き行うこと",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "抑制",
    reading: "よくせい",
    meaning: "感情や行動をおさえ、控えること",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "排除",
    reading: "はいじょ",
    meaning: "不要なものを取り除くこと",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "抽選",
    reading: "ちゅうせん",
    meaning: "くじなどで公平に選び出すこと",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "再編",
    reading: "さいへん",
    meaning: "組織や構成を改めて組み直すこと",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "照合",
    reading: "しょうごう",
    meaning: "二つ以上のものを比べて確かめること",
  },

  {
    level: "hard",
    rank: "1",
    kanji: "弁証",
    reading: "べんしょう",
    meaning: "議論によって正しさを明らかにすること",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "高揚",
    reading: "こうよう",
    meaning: "気分や意欲が高まること",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "精査",
    reading: "せいさ",
    meaning: "細かい点まで注意して調べること",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "滞納",
    reading: "たいのう",
    meaning: "期限までに納めるべきものを納めないこと",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "介在",
    reading: "かいざい",
    meaning: "二つのものの間に入り込んで存在すること",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "抽入",
    reading: "ちゅうにゅう",
    meaning: "中に差し入れること",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "堆積",
    reading: "たいせき",
    meaning: "物が積み重なってたまること",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "動揺",
    reading: "どうよう",
    meaning: "気持ちが落ち着かず揺れ動くこと",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "錯乱",
    reading: "さくらん",
    meaning: "思考や行動が混乱して正常でなくなること",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "追憶",
    reading: "ついおく",
    meaning: "過去の出来事を思い出すこと",
  },

  {
    level: "hard",
    rank: "1",
    kanji: "精妙",
    reading: "せいみょう",
    meaning: "非常に巧みで細やかなこと",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "懸架",
    reading: "けんか",
    meaning: "つり下げて支えること",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "遡及",
    reading: "そきゅう",
    meaning: "過去にさかのぼって影響を及ぼすこと",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "干渉",
    reading: "かんしょう",
    meaning: "他の物事に立ち入って影響を与えること",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "圧巻",
    reading: "あっかん",
    meaning: "全体の中で最もすぐれ、目を引くもの",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "緻密",
    reading: "ちみつ",
    meaning: "細かいところまで行き届いていること",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "拘束",
    reading: "こうそく",
    meaning: "自由な行動を制限すること",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "堅持",
    reading: "けんじ",
    meaning: "強い意志で守り続けること",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "追随",
    reading: "ついずい",
    meaning: "先に行くもののあとを追って従うこと",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "逸話",
    reading: "いつわ",
    meaning: "人物や出来事にまつわる興味深い話",
  },

  {
    level: "hard",
    rank: "1",
    kanji: "乖離",
    reading: "かいり",
    meaning: "二つのものが大きくかけ離れること",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "変遷",
    reading: "へんせん",
    meaning: "時とともに変わり移っていくこと",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "漸次",
    reading: "ぜんじ",
    meaning: "少しずつ順を追って進むこと",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "暗黙",
    reading: "あんもく",
    meaning: "はっきり言わなくても理解されていること",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "斟酌",
    reading: "しんしゃく",
    meaning: "相手の事情や気持ちをくみ取ること",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "収斂",
    reading: "しゅうれん",
    meaning: "ばらばらだったものが一つにまとまること",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "煩雑",
    reading: "はんざつ",
    meaning: "入り組んでいて面倒なこと",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "錯綜",
    reading: "さくそう",
    meaning: "複雑に入り混じっていること",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "停頓",
    reading: "ていとん",
    meaning: "物事が進まず止まってしまうこと",
  },
  {
    level: "hard",
    rank: "1",
    kanji: "灰汁",
    reading: "あく",
    meaning: "不要で取り除くべき悪い部分",
  },

  /* =======================
          rank2（上級：本格的に難しい）
         ======================= */
  {
    level: "hard",
    rank: "2",
    kanji: "煩瑣",
    reading: "はんさ",
    meaning: "物事がこみ入っていて面倒なこと",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "僭越",
    reading: "せんえつ",
    meaning: "自分の立場をわきまえず出過ぎたことをすること",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "矛盾律",
    reading: "むじゅんりつ",
    meaning:
      "同一の事柄について矛盾する命題は同時に成り立たないという論理の原理",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "形骸化",
    reading: "けいがいか",
    meaning: "内容や実質が失われ、形だけ残ること",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "峻別",
    reading: "しゅんべつ",
    meaning: "厳しくはっきりと区別すること",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "毀損",
    reading: "きそん",
    meaning: "物や信用などを傷つけ損なうこと",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "驕慢",
    reading: "きょうまん",
    meaning: "おごり高ぶって人を見下すこと",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "逼迫",
    reading: "ひっぱく",
    meaning: "差し迫って余裕がなくなること",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "穿鑿",
    reading: "せんさく",
    meaning: "細かい点まで掘り下げて調べること",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "網羅",
    reading: "もうら",
    meaning: "もれなくすべてを含むこと",
  },

  {
    level: "hard",
    rank: "2",
    kanji: "煽動",
    reading: "せんどう",
    meaning: "人の感情をあおって行動を起こさせること",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "頓挫",
    reading: "とんざ",
    meaning: "計画や物事が途中で行き詰まること",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "宥和",
    reading: "ゆうわ",
    meaning: "相手をなだめて争いを和らげること",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "詭弁",
    reading: "きべん",
    meaning: "一見もっともらしいが誤りのある議論",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "懐疑",
    reading: "かいぎ",
    meaning: "物事を疑って簡単に信じないこと",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "忖度",
    reading: "そんたく",
    meaning: "他人の気持ちや事情を推し量ること",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "越権行為",
    reading: "えっけんこうい",
    meaning: "自分の権限を超えて行動すること",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "毀誉褒貶",
    reading: "きよほうへん",
    meaning: "人や物事をほめたりけなしたりする評価",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "徒労",
    reading: "とろう",
    meaning: "苦労したのに成果が得られないこと",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "精緻化",
    reading: "せいちか",
    meaning: "より細かく正確に作り上げること",
  },

  {
    level: "hard",
    rank: "2",
    kanji: "難航",
    reading: "なんこう",
    meaning: "物事が思い通りに進まないこと",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "懲戒処分",
    reading: "ちょうかいしょぶん",
    meaning: "規則違反などに対して科される処分",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "冗長",
    reading: "じょうちょう",
    meaning: "必要以上に長くて無駄が多いこと",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "矛盾",
    reading: "むじゅん",
    meaning: "つじつまが合わず成り立たないこと",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "延滞金",
    reading: "えんたいきん",
    meaning: "支払いが遅れた場合に追加で支払うお金",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "専横",
    reading: "せんおう",
    meaning: "権力を独り占めして思い通りにふるまうこと",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "放恣",
    reading: "ほうし",
    meaning: "勝手気ままでだらしないこと",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "濫用",
    reading: "らんよう",
    meaning: "権限や制度を正しくない形で使うこと",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "専制",
    reading: "せんせい",
    meaning: "権力を一人で独占して支配すること",
  },

  {
    level: "hard",
    rank: "2",
    kanji: "簒奪",
    reading: "さんだつ",
    meaning: "本来の持ち主から権力や地位を奪い取ること",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "顧慮",
    reading: "ころ",
    meaning: "あれこれ気にかけて配慮すること",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "懐古",
    reading: "かいこ",
    meaning: "過去を思い出してなつかしむこと",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "煩瑣化",
    reading: "はんさか",
    meaning: "物事がますます複雑で面倒になること",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "僭称",
    reading: "せんしょう",
    meaning: "資格がないのに勝手に名乗ること",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "倒錯",
    reading: "とうさく",
    meaning: "正常な状態が逆転しゆがむこと",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "形而上",
    reading: "けいじじょう",
    meaning: "感覚では捉えられない抽象的な事柄",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "隠匿",
    reading: "いんとく",
    meaning: "事実や物を隠して人に知らせないこと",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "拘泥",
    reading: "こうでい",
    meaning: "一つの考えや細部にこだわりすぎること",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "憂慮",
    reading: "ゆうりょ",
    meaning: "将来を心配して気にかけること",
  },

  {
    level: "hard",
    rank: "2",
    kanji: "困憊",
    reading: "こんぱい",
    meaning: "疲れ果てて力がなくなること",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "逡巡",
    reading: "しゅんじゅん",
    meaning: "決断できずにためらうこと",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "狼狽",
    reading: "ろうばい",
    meaning: "不意の出来事に慌てふためくこと",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "憤懣",
    reading: "ふんまん",
    meaning: "怒りや不満が心にたまること",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "慨嘆",
    reading: "がいたん",
    meaning: "世の中や状況を嘆き悲しむこと",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "反駁",
    reading: "はんばく",
    meaning: "相手の主張に対して論理的に反論すること",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "排斥",
    reading: "はいせき",
    meaning: "特定の人や考えを排除すること",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "憔悴",
    reading: "しょうすい",
    meaning: "心身ともにやつれ弱ること",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "腐朽",
    reading: "ふきゅう",
    meaning: "腐って価値を失うこと、または組織の堕落",
  },
  {
    level: "hard",
    rank: "2",
    kanji: "紛糾",
    reading: "ふんきゅう",
    meaning: "意見が対立して混乱すること",
  },

  /* =======================
          rank3（上級：超難読多め）
         ======================= */
  {
    level: "hard",
    rank: "3",
    kanji: "煩悶",
    reading: "はんもん",
    meaning: "悩み苦しんで心が乱れること",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "頽廃",
    reading: "たいはい",
    meaning: "道徳や秩序が崩れてだらしなくなること",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "靄",
    reading: "もや",
    meaning: "空気中に細かい水滴やちりが漂って視界がかすむ現象",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "齟齬",
    reading: "そご",
    meaning: "物事や意見が食い違って合わないこと",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "膾炙",
    reading: "かいしゃ",
    meaning: "多くの人に広く知れ渡ること",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "瑕疵",
    reading: "かし",
    meaning: "欠点や不完全な点",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "晦渋",
    reading: "かいじゅう",
    meaning: "意味が分かりにくく難解なこと",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "隘路",
    reading: "あいろ",
    meaning: "狭くて通りにくい道",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "諧謔",
    reading: "かいぎゃく",
    meaning: "気の利いた冗談やしゃれ",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "怯懦",
    reading: "きょうだ",
    meaning: "気が弱く臆病なこと",
  },

  {
    level: "hard",
    rank: "3",
    kanji: "謬見",
    reading: "びゅうけん",
    meaning: "誤った考えや見解",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "瞠目",
    reading: "どうもく",
    meaning: "驚いて目を見張ること",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "奸計",
    reading: "かんけい",
    meaning: "悪意のあるたくらみ",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "朦朧",
    reading: "もうろう",
    meaning: "意識や物事がはっきりしないさま",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "贅沢三昧",
    reading: "ぜいたくざんまい",
    meaning: "思う存分ぜいたくをすること",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "懊悩",
    reading: "おうのう",
    meaning: "深く悩み苦しむこと",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "拮抗作用",
    reading: "きっこうさよう",
    meaning: "互いに反対の働きをして釣り合う作用",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "警句",
    reading: "けいく",
    meaning: "人の心に強く訴える短い言葉",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "朧月",
    reading: "おぼろづき",
    meaning: "春先などに霞んで見える月",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "顛末",
    reading: "てんまつ",
    meaning: "物事の始まりから終わりまでの経過",
  },

  {
    level: "hard",
    rank: "3",
    kanji: "錯綜",
    reading: "さくそう",
    meaning: "物事が複雑に入り組んでいること",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "放埒",
    reading: "ほうらつ",
    meaning: "勝手気までだらしないこと",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "竜頭蛇尾",
    reading: "りゅうとうだび",
    meaning: "初めは盛大だが終わりが振るわないこと",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "深謀遠慮",
    reading: "しんぼうえんりょ",
    meaning: "深く考え将来まで見通した計画",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "陰鬱",
    reading: "いんうつ",
    meaning: "気分が沈んで暗いこと",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "悔悟",
    reading: "かいご",
    meaning: "自分の過ちを悔いて反省すること",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "瞭然",
    reading: "りょうぜん",
    meaning: "はっきりして疑いのないさま",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "豪胆",
    reading: "ごうたん",
    meaning: "度胸があり大胆なこと",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "艱難辛苦",
    reading: "かんなんしんく",
    meaning: "非常に苦しくつらい経験",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "深淵",
    reading: "しんえん",
    meaning: "非常に深いところ、または奥深い世界",
  },

  {
    level: "hard",
    rank: "3",
    kanji: "耽溺",
    reading: "たんでき",
    meaning: "あることに溺れるほど夢中になること",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "蹉跌",
    reading: "さてつ",
    meaning: "つまずきや失敗",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "跋扈",
    reading: "ばっこ",
    meaning: "権力を振るって勝手にふるまうこと",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "僻見",
    reading: "へきけん",
    meaning: "偏った見方や考え",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "滂沱",
    reading: "ぼうだ",
    meaning: "涙や雨が激しく流れ落ちるさま",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "狷介",
    reading: "けんかい",
    meaning: "頑固で自分の意志を曲げないこと",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "悖論",
    reading: "はいろん",
    meaning: "一見正しいが実は矛盾を含む議論",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "跫音",
    reading: "きょうおん",
    meaning: "人の足音",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "衒学",
    reading: "げんがく",
    meaning: "学識をひけらかすこと",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "晦冥",
    reading: "かいめい",
    meaning: "暗くてはっきりしないこと",
  },

  {
    level: "hard",
    rank: "3",
    kanji: "瀰漫",
    reading: "びまん",
    meaning: "広く一面に広がること",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "幽玄",
    reading: "ゆうげん",
    meaning: "奥深く趣があり神秘的な美しさ",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "蹂躙",
    reading: "じゅうりん",
    meaning: "踏みにじるように荒らすこと",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "跛行",
    reading: "はこう",
    meaning: "足を引きずって歩くこと、または物事が不均衡に進むこと",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "蠢動",
    reading: "しゅんどう",
    meaning: "ひそかに動き出すこと",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "慫慂",
    reading: "しょうよう",
    meaning: "人に強く勧めて行動させること",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "迂遠",
    reading: "うえん",
    meaning: "回りくどく要点を外れていること",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "眩惑",
    reading: "げんわく",
    meaning: "目や心をくらませ惑わすこと",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "寥寥",
    reading: "りょうりょう",
    meaning: "物音や人影がなくひっそりしているさま",
  },
  {
    level: "hard",
    rank: "3",
    kanji: "冥利",
    reading: "みょうり",
    meaning: "その立場にある者として感じる大きな喜び",
  },

  {
    level: "hard",
    rank: "BOSS",
    kanji: "齷齪",
    reading: "あくせく",
    meaning: "目先のことにとらわれて落ち着きなく動き回ること",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "諫止",
    reading: "かんし",
    meaning: "過ちを改めるようにいさめ止めること",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "頽勢",
    reading: "たいせい",
    meaning: "衰え傾いていく勢い",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "辟易",
    reading: "へきえき",
    meaning: "うんざりして嫌になること",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "涵養",
    reading: "かんよう",
    meaning: "徐々に養い育てること",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "矜持",
    reading: "きょうじ、きんじ",
    meaning: "自分の能力や立場に対する誇り",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "老獪",
    reading: "ろうかい",
    meaning: "年を重ねてずる賢いこと",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "杞憂",
    reading: "きゆう",
    meaning: "必要のない心配",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "潤沢",
    reading: "じゅんたく",
    meaning: "余裕があり豊かなこと",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "慇懃",
    reading: "いんぎん",
    meaning: "態度や言葉づかいが丁寧なこと",
  },

  {
    level: "hard",
    rank: "BOSS",
    kanji: "罷免",
    reading: "ひめん",
    meaning: "職や地位を取り上げること",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "饒舌",
    reading: "じょうぜつ",
    meaning: "よくしゃべること",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "誅罰",
    reading: "ちゅうばつ",
    meaning: "罪をとがめて罰すること",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "醜悪",
    reading: "しゅうあく",
    meaning: "非常にみにくく不快なこと",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "懊恨",
    reading: "おうこん",
    meaning: "後悔して心が痛むこと",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "傲岸",
    reading: "ごうがん",
    meaning: "おごり高ぶって人を見下すこと",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "扼要",
    reading: "やくよう",
    meaning: "要点を簡潔にまとめていること",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "咀嚼",
    reading: "そしゃく",
    meaning: "内容をよく考えて理解すること",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "多弁",
    reading: "たべん",
    meaning: "言葉数が多いこと",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "欝金香",
    reading: "うこんこう",
    meaning: "チューリップの別名で、香り高い花を指す言葉",
  },

  {
    level: "hard",
    rank: "BOSS",
    kanji: "慫慂",
    reading: "しょうよう",
    meaning: "人に強く勧めて行動させること",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "晦冥",
    reading: "かいめい",
    meaning: "暗くてはっきりしないこと",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "滂沱",
    reading: "ぼうだ",
    meaning: "涙や雨などが激しく流れ落ちるさま",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "衰頽",
    reading: "すいたい",
    meaning: "衰え弱ること",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "毀壊",
    reading: "きかい",
    meaning: "壊して損なうこと",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "驟雨",
    reading: "しゅうう",
    meaning: "急に激しく降る雨",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "累卵",
    reading: "るいらん",
    meaning: "非常に危うい状態のたとえ",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "玉石混淆",
    reading: "ぎょくせきこんこう",
    meaning: "良いものと悪いものが入り混じっていること",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "無謬性",
    reading: "むびゅうせい",
    meaning: "誤りがないとされる性質",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "辣腕",
    reading: "らつわん",
    meaning: "手腕が鋭く物事を巧みに処理すること",
  },

  {
    level: "hard",
    rank: "BOSS",
    kanji: "偏執",
    reading: "へんしつ",
    meaning: "一つの考えに強くこだわること",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "驕奢",
    reading: "きょうしゃ",
    meaning: "おごり高ぶりぜいたくなこと",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "僭称",
    reading: "せんしょう",
    meaning: "身分にそぐわない称号を勝手に名乗ること",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "跋扈",
    reading: "ばっこ",
    meaning: "権力を振るって勝手にふるまうこと",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "蹉跌",
    reading: "さてつ",
    meaning: "つまずきや失敗",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "悖徳",
    reading: "はいとく",
    meaning: "道徳に反する行い",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "齎す",
    reading: "もたらす",
    meaning: "結果や影響を引き起こす",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "縷々",
    reading: "るる",
    meaning: "細かく詳しく述べるさま",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "矍鑠",
    reading: "かくしゃく",
    meaning: "年を取っても元気でしっかりしていること",
  },
  {
    level: "hard",
    rank: "BOSS",
    kanji: "嚆矢",
    reading: "こうし",
    meaning: "物事の最初のきっかけ",
  },
];

export default hardQuestions;
