const normalQuestions = [
  /* ===========================
            rank1（基本の二字熟語 50問）
         =========================== */
  {
    level: "normal",
    rank: "1",
    kanji: "計画",
    reading: "けいかく",
    meaning: "目的を達成するために前もって立てる考えや手順",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "記録",
    reading: "きろく",
    meaning: "出来事や結果を書き残すこと",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "整理",
    reading: "せいり",
    meaning: "物事を分けて整えること",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "出荷",
    reading: "しゅっか",
    meaning: "商品を送り出すこと",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "印象",
    reading: "いんしょう",
    meaning: "見たり聞いたりして心に残った感じ",
  },

  {
    level: "normal",
    rank: "1",
    kanji: "発表",
    reading: "はっぴょう",
    meaning: "人前で知らせたり示したりすること",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "反応",
    reading: "はんのう",
    meaning: "外からの刺激に対して起こる動きや変化",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "事例",
    reading: "じれい",
    meaning: "実際に起こった具体的な例",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "構図",
    reading: "こうず",
    meaning: "全体の配置や組み立ての形",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "信号",
    reading: "しんごう",
    meaning: "合図として示される光や音",
  },

  {
    level: "normal",
    rank: "1",
    kanji: "要請",
    reading: "ようせい",
    meaning: "必要なことを強くお願いすること",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "改善",
    reading: "かいぜん",
    meaning: "悪い点を改めて良くすること",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "注意",
    reading: "ちゅうい",
    meaning: "気をつけて心を向けること",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "試験",
    reading: "しけん",
    meaning: "能力や知識を確かめるために行うもの",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "制度",
    reading: "せいど",
    meaning: "社会や組織で決められた仕組み",
  },

  {
    level: "normal",
    rank: "1",
    kanji: "連続",
    reading: "れんぞく",
    meaning: "切れ目なく続くこと",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "努力",
    reading: "どりょく",
    meaning: "目標に向かって力を尽くすこと",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "回数",
    reading: "かいすう",
    meaning: "行った回の数",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "時期",
    reading: "じき",
    meaning: "ある出来事が起こるころ",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "対策",
    reading: "たいさく",
    meaning: "問題に備えて考える方法",
  },

  {
    level: "normal",
    rank: "1",
    kanji: "設定",
    reading: "せってい",
    meaning: "条件や内容を決めること",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "達成",
    reading: "たっせい",
    meaning: "目的をやりとげること",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "状況",
    reading: "じょうきょう",
    meaning: "その場の様子や状態",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "平均",
    reading: "へいきん",
    meaning: "全体を均等に分けたときの値",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "記念",
    reading: "きねん",
    meaning: "ある出来事を忘れないために残すこと",
  },

  {
    level: "normal",
    rank: "1",
    kanji: "保護",
    reading: "ほご",
    meaning: "守り助けること",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "感想",
    reading: "かんそう",
    meaning: "感じたことや思ったこと",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "意見",
    reading: "いけん",
    meaning: "自分の考えや思い",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "条件",
    reading: "じょうけん",
    meaning: "物事が成り立つための決まり",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "要素",
    reading: "ようそ",
    meaning: "全体を成り立たせている大切な部分",
  },

  {
    level: "normal",
    rank: "1",
    kanji: "特徴",
    reading: "とくちょう",
    meaning: "他と比べて目立つ点",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "現実",
    reading: "げんじつ",
    meaning: "実際に起こっていること",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "発見",
    reading: "はっけん",
    meaning: "今まで知られていなかったことを見つけること",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "比例",
    reading: "ひれい",
    meaning: "一方が増えると他方も同じ割合で増える関係",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "比較",
    reading: "ひかく",
    meaning: "違いや共通点を比べること",
  },

  {
    level: "normal",
    rank: "1",
    kanji: "結末",
    reading: "けつまつ",
    meaning: "物事の最後の結果",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "注意報",
    reading: "ちゅういほう",
    meaning: "気をつけるように知らせる情報",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "作業",
    reading: "さぎょう",
    meaning: "仕事として行う動きや働き",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "確率",
    reading: "かくりつ",
    meaning: "ある出来事が起こる可能性",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "最終",
    reading: "さいしゅう",
    meaning: "いちばん最後",
  },

  {
    level: "normal",
    rank: "1",
    kanji: "現場",
    reading: "げんば",
    meaning: "実際に物事が行われている場所",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "整理券",
    reading: "せいりけん",
    meaning: "順番を整理するために配られる券",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "重要",
    reading: "じゅうよう",
    meaning: "とても大切なこと",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "成功",
    reading: "せいこう",
    meaning: "目的を達成してうまくいくこと",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "視点",
    reading: "してん",
    meaning: "物事を見る立場や考え方",
  },

  {
    level: "normal",
    rank: "1",
    kanji: "機能",
    reading: "きのう",
    meaning: "役に立つ働き",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "用途",
    reading: "ようと",
    meaning: "使い道",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "本質",
    reading: "ほんしつ",
    meaning: "物事のいちばん大切な中身",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "改善点",
    reading: "かいぜんてん",
    meaning: "より良くするために直すべき点",
  },
  {
    level: "normal",
    rank: "1",
    kanji: "信頼度",
    reading: "しんらいど",
    meaning: "どれくらい信じられるかの度合い",
  },

  /* ===========================
            rank2（中級・少し難しい 50問）
         =========================== */
  {
    level: "normal",
    rank: "2",
    kanji: "概念",
    reading: "がいねん",
    meaning: "物事を大まかにまとめてとらえた考え",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "俯瞰",
    reading: "ふかん",
    meaning: "高いところから全体を見下ろすように物事を見ること",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "構造",
    reading: "こうぞう",
    meaning: "物事がどのような仕組みで成り立っているかという形",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "抽象",
    reading: "ちゅうしょう",
    meaning: "具体的なものから共通点を抜き出して考えること",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "推測",
    reading: "すいそく",
    meaning: "はっきりしないことを手がかりから考え出すこと",
  },

  {
    level: "normal",
    rank: "2",
    kanji: "精度",
    reading: "せいど",
    meaning: "正確さの度合い",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "根拠",
    reading: "こんきょ",
    meaning: "考えや判断のもとになる理由",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "相関",
    reading: "そうかん",
    meaning: "二つの事柄が互いに関係し合っていること",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "権限",
    reading: "けんげん",
    meaning: "あることを行うことが認められた力や範囲",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "確証",
    reading: "かくしょう",
    meaning: "確かであると証明できる証拠",
  },

  {
    level: "normal",
    rank: "2",
    kanji: "解析",
    reading: "かいせき",
    meaning: "物事を細かく分けて調べ、理解すること",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "転換",
    reading: "てんかん",
    meaning: "方向や状態を別のものに変えること",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "拡張",
    reading: "かくちょう",
    meaning: "範囲や機能を広げること",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "縮小",
    reading: "しゅくしょう",
    meaning: "大きさや範囲を小さくすること",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "志向",
    reading: "しこう",
    meaning: "ある方向や目標を目指す考え方",
  },

  {
    level: "normal",
    rank: "2",
    kanji: "施策",
    reading: "しさく",
    meaning: "目的のために行う具体的な方法",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "要件",
    reading: "ようけん",
    meaning: "必要とされる条件",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "関連",
    reading: "かんれん",
    meaning: "互いにつながりがあること",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "変革",
    reading: "へんかく",
    meaning: "仕組みや考え方を大きく変えること",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "企画",
    reading: "きかく",
    meaning: "計画を立てて実行を考えること",
  },

  {
    level: "normal",
    rank: "2",
    kanji: "抑制",
    reading: "よくせい",
    meaning: "行きすぎないようにおさえること",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "制御",
    reading: "せいぎょ",
    meaning: "思い通りに動かすように調整すること",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "分配",
    reading: "ぶんぱい",
    meaning: "全体を分けて配ること",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "調整",
    reading: "ちょうせい",
    meaning: "ちょうどよく整えること",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "構築",
    reading: "こうちく",
    meaning: "組み立てて作り上げること",
  },

  {
    level: "normal",
    rank: "2",
    kanji: "確立",
    reading: "かくりつ",
    meaning: "しっかりと定まって動かない状態にすること",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "反証",
    reading: "はんしょう",
    meaning: "相手の主張が誤りだと示す証拠",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "推論",
    reading: "すいろん",
    meaning: "情報をもとに考えを進めて結論を出すこと",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "施行",
    reading: "しこう",
    meaning: "決めたことを実際に行うこと",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "精査",
    reading: "せいさ",
    meaning: "細かい点までくわしく調べること",
  },

  {
    level: "normal",
    rank: "2",
    kanji: "概要",
    reading: "がいよう",
    meaning: "全体の大まかな内容",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "適応",
    reading: "てきおう",
    meaning: "環境や状況に合うように変わること",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "補足",
    reading: "ほそく",
    meaning: "足りない説明を付け加えること",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "克服",
    reading: "こくふく",
    meaning: "困難や弱点を乗り越えること",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "創造",
    reading: "そうぞう",
    meaning: "新しいものを生み出すこと",
  },

  {
    level: "normal",
    rank: "2",
    kanji: "理論",
    reading: "りろん",
    meaning: "物事を筋道立てて説明する考え",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "傾向",
    reading: "けいこう",
    meaning: "物事が進みやすい方向や様子",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "特殊",
    reading: "とくしゅ",
    meaning: "他と比べて特別であること",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "規制",
    reading: "きせい",
    meaning: "決まりによって制限すること",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "対立",
    reading: "たいりつ",
    meaning: "意見や立場が向かい合って争うこと",
  },

  {
    level: "normal",
    rank: "2",
    kanji: "抽出",
    reading: "ちゅうしゅつ",
    meaning: "必要な部分だけを取り出すこと",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "均衡",
    reading: "きんこう",
    meaning: "全体がつり合っていること",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "指針",
    reading: "ししん",
    meaning: "進む方向を示す考えや基準",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "媒介",
    reading: "ばいかい",
    meaning: "両者の間に立ってつなぐこと",
  },
  {
    level: "normal",
    rank: "2",
    kanji: "概略",
    reading: "がいりゃく",
    meaning: "細かい点を省いた大まかな説明",
  },

  /* ===========================
            rank3（高度な二字熟語 50問）
         =========================== */
  {
    level: "normal",
    rank: "3",
    kanji: "端緒",
    reading: "たんしょ",
    meaning: "物事が始まるきっかけ",
  },
  {
    level: "normal",
    rank: "3",
    kanji: "兆候",
    reading: "ちょうこう",
    meaning: "これから起こりそうなことを予想させるしるし",
  },
  {
    level: "normal",
    rank: "3",
    kanji: "旋回",
    reading: "せんかい",
    meaning: "円を描くように回ること",
  },
  {
    level: "normal",
    rank: "3",
    kanji: "遵守",
    reading: "じゅんしゅ",
    meaning: "決まりや約束をきちんと守ること",
  },
  {
    level: "normal",
    rank: "3",
    kanji: "精緻",
    reading: "せいち",
    meaning: "非常に細かく、よくできていること",
  },

  {
    level: "normal",
    rank: "3",
    kanji: "希薄",
    reading: "きはく",
    meaning: "薄くて少ないこと、関わりが弱いこと",
  },
  {
    level: "normal",
    rank: "3",
    kanji: "緩衝",
    reading: "かんしょう",
    meaning: "衝撃や対立をやわらげること",
  },
  {
    level: "normal",
    rank: "3",
    kanji: "堅実",
    reading: "けんじつ",
    meaning: "確実で手堅いこと",
  },
  {
    level: "normal",
    rank: "3",
    kanji: "追従",
    reading: "ついじゅう",
    meaning: "後について従うこと",
  },
  {
    level: "normal",
    rank: "3",
    kanji: "抽象化",
    reading: "ちゅうしょうか",
    meaning: "具体的なものから共通点を取り出してまとめること",
  },

  {
    level: "normal",
    rank: "3",
    kanji: "災禍",
    reading: "さいか",
    meaning: "大きな災害や不幸な出来事",
  },
  {
    level: "normal",
    rank: "3",
    kanji: "遵法",
    reading: "じゅんぽう",
    meaning: "法律を守ること",
  },
  {
    level: "normal",
    rank: "3",
    kanji: "確執",
    reading: "かくしつ",
    meaning: "意見の食い違いによる深い対立",
  },
  {
    level: "normal",
    rank: "3",
    kanji: "端正",
    reading: "たんせい",
    meaning: "姿や形が整っていて美しいこと",
  },
  {
    level: "normal",
    rank: "3",
    kanji: "機微",
    reading: "きび",
    meaning: "人の心や物事の微妙な動き",
  },

  {
    level: "normal",
    rank: "3",
    kanji: "瞬発",
    reading: "しゅんぱつ",
    meaning: "瞬間的に力を発揮すること",
  },
  {
    level: "normal",
    rank: "3",
    kanji: "本質",
    reading: "ほんしつ",
    meaning: "物事の根本的な性質",
  },
  {
    level: "normal",
    rank: "3",
    kanji: "冗長",
    reading: "じょうちょう",
    meaning: "無駄が多く、長すぎること",
  },
  {
    level: "normal",
    rank: "3",
    kanji: "緻密",
    reading: "ちみつ",
    meaning: "細かいところまでよく行き届いていること",
  },
  {
    level: "normal",
    rank: "3",
    kanji: "概況",
    reading: "がいきょう",
    meaning: "全体の大まかな様子",
  },

  {
    level: "normal",
    rank: "3",
    kanji: "精巧",
    reading: "せいこう",
    meaning: "非常に細かく、巧みに作られていること",
  },
  {
    level: "normal",
    rank: "3",
    kanji: "権勢",
    reading: "けんせい",
    meaning: "権力とそれに伴う強い影響力",
  },
  {
    level: "normal",
    rank: "3",
    kanji: "主導",
    reading: "しゅどう",
    meaning: "中心となって引っ張っていくこと",
  },
  {
    level: "normal",
    rank: "3",
    kanji: "兼用",
    reading: "けんよう",
    meaning: "一つの物を二つ以上の目的に使うこと",
  },
  {
    level: "normal",
    rank: "3",
    kanji: "均質",
    reading: "きんしつ",
    meaning: "性質や内容が同じでそろっていること",
  },

  {
    level: "normal",
    rank: "3",
    kanji: "堅守",
    reading: "けんしゅ",
    meaning: "固く守り続けること",
  },
  {
    level: "normal",
    rank: "3",
    kanji: "精励",
    reading: "せいれい",
    meaning: "力を尽くして一生懸命に励むこと",
  },
  {
    level: "normal",
    rank: "3",
    kanji: "慎重",
    reading: "しんちょう",
    meaning: "注意深く、軽々しく行動しないこと",
  },
  {
    level: "normal",
    rank: "3",
    kanji: "真偽",
    reading: "しんぎ",
    meaning: "本当かうそかということ",
  },
  {
    level: "normal",
    rank: "3",
    kanji: "固執",
    reading: "こしつ",
    meaning: "自分の考えや立場に強くこだわること",
  },

  {
    level: "normal",
    rank: "3",
    kanji: "端的",
    reading: "たんてき",
    meaning: "要点を押さえて簡潔なこと",
  },
  {
    level: "normal",
    rank: "3",
    kanji: "折衷",
    reading: "せっちゅう",
    meaning: "異なる意見を取り入れて中間をとること",
  },
  {
    level: "normal",
    rank: "3",
    kanji: "調和性",
    reading: "ちょうわせい",
    meaning: "全体がうまくつり合ってまとまる性質",
  },
  {
    level: "normal",
    rank: "3",
    kanji: "妥協",
    reading: "だきょう",
    meaning: "互いに譲り合ってまとめること",
  },
  {
    level: "normal",
    rank: "3",
    kanji: "明瞭",
    reading: "めいりょう",
    meaning: "はっきりしていて分かりやすいこと",
  },

  /* ===========================
            BOSS（中級最難：二字熟語 50問）
         =========================== */
  {
    level: "normal",
    rank: "BOSS",
    kanji: "該当",
    reading: "がいとう",
    meaning: "条件や内容に当てはまること",
  },
  {
    level: "normal",
    rank: "BOSS",
    kanji: "端緒",
    reading: "たんしょ",
    meaning: "物事が始まるきっかけ",
  },
  {
    level: "normal",
    rank: "BOSS",
    kanji: "精密",
    reading: "せいみつ",
    meaning: "細かいところまで正確であること",
  },
  {
    level: "normal",
    rank: "BOSS",
    kanji: "緻密",
    reading: "ちみつ",
    meaning: "非常に細かく、念入りであること",
  },
  {
    level: "normal",
    rank: "BOSS",
    kanji: "追随",
    reading: "ついずい",
    meaning: "後を追って従うこと",
  },

  {
    level: "normal",
    rank: "BOSS",
    kanji: "端麗",
    reading: "たんれい",
    meaning: "姿や形が整っていて美しいこと",
  },
  {
    level: "normal",
    rank: "BOSS",
    kanji: "峻別",
    reading: "しゅんべつ",
    meaning: "厳しく区別すること",
  },
  {
    level: "normal",
    rank: "BOSS",
    kanji: "希求",
    reading: "ききゅう",
    meaning: "強く求め願うこと",
  },
  {
    level: "normal",
    rank: "BOSS",
    kanji: "指向",
    reading: "しこう",
    meaning: "ある方向や目的に向かうこと",
  },
  {
    level: "normal",
    rank: "BOSS",
    kanji: "明察",
    reading: "めいさつ",
    meaning: "物事をはっきりと見抜くこと",
  },

  {
    level: "normal",
    rank: "BOSS",
    kanji: "包含",
    reading: "ほうがん",
    meaning: "中に含み持つこと",
  },
  {
    level: "normal",
    rank: "BOSS",
    kanji: "端正",
    reading: "たんせい",
    meaning: "整っていて品があること",
  },
  {
    level: "normal",
    rank: "BOSS",
    kanji: "精鋭",
    reading: "せいえい",
    meaning: "選び抜かれた優秀な人や集団",
  },
  {
    level: "normal",
    rank: "BOSS",
    kanji: "遵守",
    reading: "じゅんしゅ",
    meaning: "決まりや規則をきちんと守ること",
  },
  {
    level: "normal",
    rank: "BOSS",
    kanji: "均衡",
    reading: "きんこう",
    meaning: "全体のつり合いが取れていること",
  },

  {
    level: "normal",
    rank: "BOSS",
    kanji: "錯覚",
    reading: "さっかく",
    meaning: "実際とは違って感じたり思い込んだりすること",
  },
  {
    level: "normal",
    rank: "BOSS",
    kanji: "抽出",
    reading: "ちゅうしゅつ",
    meaning: "必要な部分だけを取り出すこと",
  },
  {
    level: "normal",
    rank: "BOSS",
    kanji: "緩和",
    reading: "かんわ",
    meaning: "厳しさや緊張をやわらげること",
  },
  {
    level: "normal",
    rank: "BOSS",
    kanji: "堅持",
    reading: "けんじ",
    meaning: "考えや立場を固く守り続けること",
  },
  {
    level: "normal",
    rank: "BOSS",
    kanji: "俯瞰図",
    reading: "ふかんず",
    meaning: "全体を上から見渡した図",
  },

  {
    level: "normal",
    rank: "BOSS",
    kanji: "端境期",
    reading: "はざかいき",
    meaning: "物事の移り変わりの中間の時期",
  },
  {
    level: "normal",
    rank: "BOSS",
    kanji: "希薄",
    reading: "きはく",
    meaning: "薄くて少ないこと、関係が弱いこと",
  },
  {
    level: "normal",
    rank: "BOSS",
    kanji: "要旨",
    reading: "ようし",
    meaning: "内容の大切なポイント",
  },
  {
    level: "normal",
    rank: "BOSS",
    kanji: "精読",
    reading: "せいどく",
    meaning: "注意深く丁寧に読むこと",
  },
  {
    level: "normal",
    rank: "BOSS",
    kanji: "潜在",
    reading: "せんざい",
    meaning: "表に出ていないが内に秘めていること",
  },

  {
    level: "normal",
    rank: "BOSS",
    kanji: "簡潔",
    reading: "かんけつ",
    meaning: "無駄がなく分かりやすいこと",
  },
  {
    level: "normal",
    rank: "BOSS",
    kanji: "端緒探し",
    reading: "たんしょさがし",
    meaning: "物事を始めるきっかけを探すこと",
  },
  {
    level: "normal",
    rank: "BOSS",
    kanji: "慎重策",
    reading: "しんちょうさく",
    meaning: "失敗しないよう注意深く立てた方法",
  },
  {
    level: "normal",
    rank: "BOSS",
    kanji: "適正化",
    reading: "てきせいか",
    meaning: "適切な状態に整えること",
  },
  {
    level: "normal",
    rank: "BOSS",
    kanji: "均質化",
    reading: "きんしつか",
    meaning: "性質や内容を同じ状態にそろえること",
  },

  {
    level: "normal",
    rank: "BOSS",
    kanji: "高精度",
    reading: "こうせいど",
    meaning: "非常に正確で誤差が少ないこと",
  },
  {
    level: "normal",
    rank: "BOSS",
    kanji: "基準値",
    reading: "きじゅんち",
    meaning: "判断や比較のもとになる数値",
  },
  {
    level: "normal",
    rank: "BOSS",
    kanji: "抽象度",
    reading: "ちゅうしょうど",
    meaning: "どれだけ具体性を離れているかの度合い",
  },
  {
    level: "normal",
    rank: "BOSS",
    kanji: "端末操作",
    reading: "たんまつそうさ",
    meaning: "機械や装置を実際に扱うこと",
  },
  {
    level: "normal",
    rank: "BOSS",
    kanji: "要点整理",
    reading: "ようてんせいり",
    meaning: "大切なポイントをまとめて分かりやすくすること",
  },

  {
    level: "normal",
    rank: "BOSS",
    kanji: "状況整理",
    reading: "じょうきょうせいり",
    meaning: "今の状態や流れをまとめて把握すること",
  },
  {
    level: "normal",
    rank: "BOSS",
    kanji: "精密度",
    reading: "せいみつど",
    meaning: "どれほど正確で細かいかの度合い",
  },
  {
    level: "normal",
    rank: "BOSS",
    kanji: "概算値",
    reading: "がいさんち",
    meaning: "おおよその計算で出した数値",
  },
  {
    level: "normal",
    rank: "BOSS",
    kanji: "分析法",
    reading: "ぶんせきほう",
    meaning: "物事を詳しく調べるための方法",
  },
  {
    level: "normal",
    rank: "BOSS",
    kanji: "比較研究",
    reading: "ひかくけんきゅう",
    meaning: "複数のものを比べて調べる研究",
  },
];

export default normalQuestions;
