export const famousPersons = [
  /* =========================
     海外の偉人（カタカナ可）
     ========================= */

  {
    name: "アインシュタイン",
    image: "/images/famous/アルベルトアインシュタイン.jpg",
    difficulty: "normal",
    aliases: ["アルベルト・アインシュタイン"],
  },
  {
    name: "ガンディー",
    image: "/images/famous/ガンディー.jpg",
    difficulty: "normal",
    aliases: ["ガンジー", "マハトマ・ガンディー", "マハトマ・ガンジー"],
  },
  {
    name: "ジャンヌダルク",
    image: "/images/famous/ジャンヌ・ダルク.jpg",
    difficulty: "normal",
    aliases: ["ジャンヌ・ダルク"],
  },
  {
    name: "ウォルト・ディズニー",
    image: "/images/famous/ウォルト・ディズニー.jpg",
    difficulty: "normal",
    aliases: ["ディズニー"],
  },
  {
    name: "マリー・キュリー",
    image: "/images/famous/キュリー夫人.jpg",
    difficulty: "normal",
    aliases: ["マリ・キュリー", "マリキュリー", "マリーキュリー"],
  },
  {
    name: "ケネディ",
    image: "/images/famous/ケネディ.jpg",
    difficulty: "normal",
    aliases: ["ジョン・F・ケネディ"],
  },
  {
    name: "ニュートン",
    image: "/images/famous/アイザック・ニュートン.jpg",
    difficulty: "normal",
    aliases: ["アイザック・ニュートン"],
  },
  {
    name: "リンカン",
    image: "/images/famous/アブラハム・リンカーン.jpg",
    difficulty: "normal",
    aliases: ["リンカーン", "アブラハム・リンカーン", "アブラハム・リンカン"],
  },
  {
    name: "ダーウィン",
    image: "/images/famous/ダーウィン.jpg",
    difficulty: "normal",
    aliases: ["チャールズ・ダーウィン"],
  },
  {
    name: "ナポレオン",
    image: "/images/famous/ナポレオン・ボナパルト.jpg",
    difficulty: "normal",
    aliases: ["ナポレオン・ボナパルト"],
  },
  {
    name: "ガリレオ",
    image: "/images/famous/ガリレオ・ガリレイ.jpg",
    difficulty: "normal",
    aliases: ["ガリレオ・ガリレイ","ガリレオガリレイ"],
  },
  {
    name: "コロンブス",
    image: "/images/famous/コロンブス.jpg",
    difficulty: "normal",
  },
  {
    name: "ベートーベン",
    image: "/images/famous/ベートーヴェン.jpg",
    difficulty: "normal",
    aliases: ["ベートーヴェン"],
  },
  {
    name: "モーツァルト",
    image: "/images/famous/モーツァルト.jpg",
    difficulty: "normal",
  },
  {
    name: "シェイクスピア",
    image: "/images/famous/シェイクスピア.jpg",
    difficulty: "normal",
    aliases: ["ウィリアム・シェイクスピア"],
  },
  {
    name: "ワシントン",
    image: "/images/famous/ジョージ・ワシントン.jpg",
    difficulty: "normal",
    aliases: ["ジョージ・ワシントン", "ジョージワシントン"],
  },
  {
    name: "ロック",
    image: "/images/famous/ジョン・ロック.jpg",
    difficulty: "normal",
    aliases: ["ジョン・ロック"],
  },
  {
    name: "エリザベス一世",
    image: "/images/famous/エリザベス一世.jpg",
    difficulty: "normal",
    aliases: ["エリザベス"],
  },
  {
    name: "ダクラス・マッカーサー",
    image: "/images/famous/ダクラス・マッカーサー.jpg",
    difficulty: "normal",
    aliases: ["ダクラスマッカーサー","マッカーサー"],
  },
  {
    name: "トーマス・エジソン",
    image: "/images/famous/トーマス・エジソン.jpg",
    difficulty: "normal",
    aliases: ["トーマスエジソン","エジソン"],
  },
  {
    name: "ビスマルク",
    image: "/images/famous/ビスマルク.jpg",
    difficulty: "normal",
    aliases: ["オットー・フォン・ビスマルク","オットー・ビスマルク"],
  },
  {
    name: "スターリン",
    image: "/images/famous/スターリン.jpg",
    difficulty: "normal",
    aliases: ["ヨシフ・スターリン","ヨシフ・ヴィサリオノヴィチ・スターリン"],
  },
  {
    name: "フィンセント・ファン・ゴッホ",
    image: "/images/famous/フィンセント・ファン・ゴッホ.jpg",
    difficulty: "normal",
    aliases: ["ゴッホ","フィンセント・ゴッホ","ファン・ゴッホ","フィンセントゴッホ"],
  },
  {
    name: "フビライ・ハン",
    image: "/images/famous/フビライ・ハン.jpg",
    difficulty: "normal",
    aliases: ["クビライ・ハン","フビライハン","クビライハン"],
  },
  {
    name: "フランクリン・ルーズヴェルト",
    image: "/images/famous/フランクリン・ルーズヴェルト.jpg",
    difficulty: "normal",
    aliases: ["ルーズヴェルト","フランクリンルーズヴェルト","フランクリン・ローズべルト","フランクリンローズべルト","ローズヴェルト","ルーズべルト","ローズべルト"],
  },
  {
    name: "フランシスコ・ザビエル",
    image: "/images/famous/フランシスコ・ザビエル.jpg",
    difficulty: "normal",
    aliases: ["ザビエル","フランシスコ・ハビエル","フランシスコザビエル"],
  },
  {
    name: "フローレンス・ナイチンゲール",
    image: "/images/famous/フローレンス・ナイチンゲール.jpg",
    difficulty: "normal",
    aliases: ["ナイチンゲール","フローレンスナイチンゲール"],
  },
  {
    name: "ペリー",
    image: "/images/famous/ペリー.jpg",
    difficulty: "normal",
    aliases: ["マシュー・ペリー","マシューペリー"],
  },
  {
    name: "ホー・チミン",
    image: "/images/famous/ホー・チミン.jpg",
    difficulty: "normal",
    aliases: ["ホーチミン"],
  },
  {
    name: "マザー・テレサ",
    image: "/images/famous/マザー・テレサ.jpg",
    difficulty: "normal",
    aliases: ["マザーテレサ"],
  },
  {
    name: "マゼラン",
    image: "/images/famous/マゼラン.jpg",
    difficulty: "normal",
    aliases: ["フェルディナンド・マゼラン"],
  },
  {
    name: "マリー・アントワネット",
    image: "/images/famous/マリー・アントワネット.jpg",
    difficulty: "normal",
    aliases: ["マリーアントワネット","マリー"],
  },
  {
    name: "マルクス",
    image: "/images/famous/マルクス.jpg",
    difficulty: "normal",
    aliases: ["カール・マルクス","カールマルクス"],
  },
  {
    name: "ムッソリーニ",
    image: "/images/famous/ムッソリーニ.jpg",
    difficulty: "normal",
    aliases: ["ベニート・ムッソリーニ"],
  },
  {
    name: "モンテスキュー",
    image: "/images/famous/モンテスキュー.jpg",
    difficulty: "normal",
    aliases: ["シャルル・ド・モンテスキュー"],
  },
  {
    name: "ルイ14世",
    image: "/images/famous/ルイ14世.jpg",
    difficulty: "normal",
  },
  {
    name: "ライト兄弟",
    image: "/images/famous/ライト兄弟.jpg",
    difficulty: "normal",
  },
  {
    name: "レオナルド・ダ・ヴィンチ",
    image: "/images/famous/レオナルド・ダ・ヴィンチ.jpg",
    difficulty: "normal",
    aliases: ["レオナルドダヴィンチ","レオナルド・ダ・ビンチ","ダ・ヴィンチ"],
  },
  {
    name: "ルソー",
    image: "/images/famous/ルソー.jpg",
    difficulty: "normal",
    aliases: ["ジャン＝ジャック・ルソー","ジャン・ジャック・ルソー"],
  },
  {
    name: "ルター",
    image: "/images/famous/ルター.jpg",
    difficulty: "normal",
    aliases: ["マルティン・ルター"],
},
  {
    name: "がんじん",
    image: "/images/famous/鑑真.jpg",
    difficulty: "normal",
  },
  {
    name: "ろじん",
    image: "/images/famous/魯迅.jpg",
    difficulty: "normal",
    aliases: ["ルーシュン","魯迅"],
  },
  {
    name: "もうたくとう",
    image: "/images/famous/毛沢東.jpg",
    difficulty: "normal",
    aliases: ["毛沢東"],
  },
  {
    name: "孫文",
    image: "/images/famous/孫文.jpg",
    difficulty: "normal",
    aliases: ["そんぶん"],
  },
  {
    name: "始皇帝",
    image: "/images/famous/始皇帝.jpg",
    difficulty: "normal",
    aliases: ["しこうてい","秦の始皇帝"],
  },
  {
    name: "諸葛亮孔明",
    image: "/images/famous/諸葛亮孔明.jpg",
    difficulty: "normal",
    aliases: ["しょかつりょうこうめい","こうめい","孔明","諸葛亮","しょかつりょう","しょかつこうめい"],
  },
  {
    name: "蔣介石",
    image: "/images/famous/蔣介石.jpg",
    difficulty: "normal",
    aliases: ["しょうかいせき"],
  },
  /* =========================
     日本の偉人（ひらがな）
     ========================= */

  {
    name: "おだのぶなが",
    image: "/images/famous/織田信長.jpg",
    difficulty: "normal",
     aliases: ["織田信長"],
  },
  {
    name: "とよとみひでよし",
    image: "/images/famous/豊臣秀吉.jpg",
    difficulty: "normal",
    aliases: ["はしばひでよし","豊臣秀吉","羽柴秀吉"],
  },
  {
    name: "とくがわいえやす",
    image: "/images/famous/徳川家康.jpg",
    difficulty: "normal",
     aliases: ["徳川家康"],
  },
  {
    name: "さかもとりょうま",
    image: "/images/famous/坂本龍馬.jpg",
    difficulty: "normal",
     aliases: ["坂本龍馬"],
  },
  {
    name: "さいごうたかもり",
    image: "/images/famous/西郷隆盛.jpg",
    difficulty: "normal",
     aliases: ["西郷隆盛"],
  },
  {
    name: "おおくぼとしみち",
    image: "/images/famous/大久保利通.jpg",
    difficulty: "normal",
     aliases: ["大久保利通"],
  },
  {
    name: "きどたかよし",
    image: "/images/famous/木戸孝允.jpg",
    difficulty: "boss",
     aliases: ["木戸孝允"],
  },
  {
    name: "とくがわよしのぶ",
    image: "/images/famous/徳川慶喜.jpg",
    difficulty: "boss",
     aliases: ["徳川慶喜"],
  },
  {
    name: "いとうひろぶみ",
    image: "/images/famous/伊藤博文.jpg",
    difficulty: "normal",
     aliases: ["伊藤博文"],
  },
  {
    name: "ふくざわゆきち",
    image: "/images/famous/福沢諭吉.jpg",
    difficulty: "normal",
     aliases: ["福沢諭吉"],
  },
  {
    name: "なつめそうせき",
    image: "/images/famous/夏目漱石.jpg",
    difficulty: "normal",
     aliases: ["夏目漱石"],
  },
  {
    name: "もりおうがい",
    image: "/images/famous/森鴎外.jpg",
    difficulty: "normal",
     aliases: ["森鷗外"],
  },
  {
    name: "よさのあきこ",
    image: "/images/famous/与謝野晶子.jpg",
    difficulty: "boss",
     aliases: ["与謝野晶子"],
  },
  {
    name: "きたさとしばさぶろう",
    image: "/images/famous/北里柴三郎.jpg",
    difficulty: "boss",
     aliases: ["北里柴三郎"],
  },
  {
    name: "しぶさわえいいち",
    image: "/images/famous/渋沢栄一.jpg",
    difficulty: "boss",
     aliases: ["渋沢栄一"],
  },
  {
    name: "いわくらともみ",
    image: "/images/famous/岩倉具視.jpg",
    difficulty: "boss",
     aliases: ["岩倉具視"],
  },
  {
    name: "むつむねみつ",
    image: "/images/famous/陸奥宗光.jpg",
    difficulty: "normal",
     aliases: ["陸奥宗光"],
  },
  {
    name: "のぐちひでよ",
    image: "/images/famous/野口英世.jpg",
    difficulty: "normal",
     aliases: ["野口英世"],
  },
  {
    name: "もうりもとなり",
    image: "/images/famous/毛利元就.jpg",
    difficulty: "normal",
     aliases: ["毛利元就"],
  },
  {
    name: "あけちみつひで",
    image: "/images/famous/明智光秀.jpg",
    difficulty: "normal",
     aliases: ["明智光秀"],
  },
  {
    name: "もとおりのりなが",
    image: "/images/famous/本居宣長.jpg",
    difficulty: "normal",
     aliases: ["本居宣長"],
  },
  {
    name: "ほりたつお",
    image: "/images/famous/堀辰雄.jpg",
    difficulty: "normal",
     aliases: ["堀辰雄"],
  },
  {
    name: "ほうじょうまさこ",
    image: "/images/famous/北条政子.jpg",
    difficulty: "normal",
     aliases: ["北条政子"],
  },
  {
    name: "ほうじょうときむね",
    image: "/images/famous/北条時宗.jpg",
    difficulty: "normal",
     aliases: ["北条時宗"],
  },
  {
    name: "ひらつからいちょう",
    image: "/images/famous/平塚らいてう.jpg",
    difficulty: "normal",
    aliases: ["ひらつからいてう","平塚らいてう","平塚らいちょう"],
  },
  {
    name: "たいらのきよもり",
    image: "/images/famous/平清盛.jpg",
    difficulty: "normal",
     aliases: ["平清盛"],
  },
  {
    name: "たけだしんげん",
    image: "/images/famous/武田信玄.jpg",
    difficulty: "normal",
     aliases: ["武田信玄"],
  },
  {
    name: "ひぐちいちよう",
    image: "/images/famous/樋口一葉.jpg",
    difficulty: "normal",
     aliases: ["樋口一葉"],
  },
  {
    name: "ひみこ",
    image: "/images/famous/卑弥呼.jpg",
    difficulty: "normal",
     aliases: ["卑弥呼"],
  },
  {
    name: "いたがきたいすけ",
    image: "/images/famous/板垣退助.jpg",
    difficulty: "normal",
     aliases: ["板垣退助"],
  },
  {
    name: "伊達政宗",
    image: "/images/famous/伊達政宗.jpg",
    difficulty: "normal",
    aliases: ["だてまさむね"],
  },
  {
    name: "伊能忠敬",
    image: "/images/famous/伊能忠敬.jpg",
    difficulty: "normal",
    aliases: ["いのうただたか"],
  },
  {
    name: "歌川広重",
    image: "/images/famous/歌川広重.jpg",
    difficulty: "normal",
    aliases: ["うたがわひろしげ","安藤広重","あんどうひろしげ"],
  },
  {
    name: "芥川龍之介",
    image: "/images/famous/芥川龍之介.jpg",
    difficulty: "normal",
    aliases: ["あくたがわりゅうのすけ"],
  },
  {
    name: "梶井基次郎",
    image: "/images/famous/梶井基次郎.jpg",
    difficulty: "normal",
    aliases: ["かじいもとじろう"],
  },
  {
    name: "吉田松陰",
    image: "/images/famous/吉田松陰.jpg",
    difficulty: "normal",
    aliases: ["よしだしょういん"],
  },
  {
    name: "葛飾北斎",
    image: "/images/famous/葛飾北斎.jpg",
    difficulty: "normal",
    aliases: ["かつしかほくさい"],
  },
  {
    name: "吉田茂",
    image: "/images/famous/吉田茂.jpg",
    difficulty: "normal",
    aliases: ["よしだしげる"],
  },
  {
    name: "宮沢賢治",
    image: "/images/famous/宮沢賢治.jpg",
    difficulty: "normal",
    aliases: ["みやざわけんじ"],
  },
  {
    name: "近松門左衛門",
    image: "/images/famous/近松門左衛門.jpg",
    difficulty: "normal",
    aliases: ["ちかまつもんざえもん"],
  },
  {
    name: "こんどういさみ",
    image: "/images/famous/近藤勇.jpg",
    difficulty: "normal",
    aliases: ["近藤勇"],
  },
  {
    name: "空海",
    image: "/images/famous/空海.jpg",
    difficulty: "normal",
    aliases: ["くうかい"],
  },
  {
    name: "原敬",
    image: "/images/famous/原敬.jpg",
    difficulty: "normal",
    aliases: ["はらたかし"],
  },
  {
    name: "源義経",
    image: "/images/famous/源義経.jpg",
    difficulty: "normal",
    aliases: ["みなもとのよしつね"],
  },
  {
    name: "源実朝",
    image: "/images/famous/源実朝.jpg",
    difficulty: "boss",
    aliases: ["みなもとのさねとも"],
  },
  {
    name: "源頼朝",
    image: "/images/famous/源頼朝.jpg",
    difficulty: "normal",
    aliases: ["みなもとのよりとも"],
  },
  {
    name: "後醍醐天皇",
    image: "/images/famous/後醍醐天皇.jpg",
    difficulty: "normal",
    aliases: ["ごだいごてんのう"],
  },
  {
    name: "高杉晋作",
    image: "/images/famous/高杉晋作.jpg",
    difficulty: "normal",
    aliases: ["たかすぎしんさく"],
  },
  {
    name: "国木田独歩",
    image: "/images/famous/国木田独歩.jpg",
    difficulty: "normal",
    aliases: ["くにきだどっぽ"],
  },
  {
    name: "手塚治虫",
    image: "/images/famous/手塚治虫.jpg",
    difficulty: "normal",
    aliases: ["てづかおさむ"],
  },
  {
    name: "勝海舟",
    image: "/images/famous/勝海舟.jpg",
    difficulty: "normal",
    aliases: ["かつかいしゅう"],
  },{
    name: "小村寿太郎",
    image: "/images/famous/小村寿太郎.jpg",
    difficulty: "normal",
    aliases: ["こむらじゅたろう"],
  },{
    name: "小野妹子",
    image: "/images/famous/小野妹子.jpg",
    difficulty: "normal",
    aliases: ["おののいもこ"],
  },{
    name: "松尾芭蕉",
    image: "/images/famous/松尾芭蕉.jpg",
    difficulty: "normal",
    aliases: ["まつおばしょう"],
  },
  {
    name: "上杉謙信",
    image: "/images/famous/上杉謙信.jpg",
    difficulty: "normal",
    aliases: ["うえすぎけんしん"],
  },
  {
    name: "真田幸村",
    image: "/images/famous/真田幸村.jpg",
    difficulty: "normal",
    aliases: ["さなだゆきむら"],
  },
  {
    name: "杉原千畝",
    image: "/images/famous/杉原千畝.jpg",
    difficulty: "normal",
    aliases: ["すぎはらちうね"],
  },
  {
    name: "杉田玄白",
    image: "/images/famous/杉田玄白.jpg",
    difficulty: "normal",
    aliases: ["すぎたげんぱく"],
  },
  {
    name: "菅原道真",
    image: "/images/famous/菅原道真.jpg",
    difficulty: "normal",
    aliases: ["すがわらのみちざね"],
  },
  {
    name: "正岡子規",
    image: "/images/famous/正岡子規.jpg",
    difficulty: "normal",
    aliases: ["まさおかしき"],
  },
  {
    name: "清少納言",
    image: "/images/famous/清少納言.jpg",
    difficulty: "normal",
    aliases: ["せいしょうなごん"],
  },
  {
    name: "聖徳太子",
    image: "/images/famous/聖徳太子.jpg",
    difficulty: "normal",
    aliases: ["しょうとくたいし"],
  },
  {
    name: "千利休",
    image: "/images/famous/千利休.jpg",
    difficulty: "normal",
    aliases: ["せんのりきゅう"],
  },
  {
    name: "足利義政",
    image: "/images/famous/足利義政.jpg",
    difficulty: "normal",
    aliases: ["あしかがよしまさ"],
  },
  {
    name: "足利義満",
    image: "/images/famous/足利義満.jpg",
    difficulty: "normal",
    aliases: ["あしかがよしみつ"],
  },
  {
    name: "足利尊氏",
    image: "/images/famous/足利尊氏.jpg",
    difficulty: "normal",
    aliases: ["あしかがたかうじ"],
  },
  {
    name: "太宰治",
    image: "/images/famous/太宰治.jpg",
    difficulty: "normal",
    aliases: ["だざいおさむ"],
  },
  {
    name: "大塩平八郎",
    image: "/images/famous/大塩平八郎.jpg",
    difficulty: "normal",
    aliases: ["おおしおへいはちろう"],
  },
  {
    name: "大隈重信",
    image: "/images/famous/大隈重信.jpg",
    difficulty: "normal",
    aliases: ["おおくましげのぶ"],
  },
  {
    name: "滝廉太郎",
    image: "/images/famous/滝廉太郎.jpg",
    difficulty: "normal",
    aliases: ["たきれんたろう"],
  },
  {
    name: "津田梅子",
    image: "/images/famous/津田梅子.jpg",
    difficulty: "normal",
    aliases: ["つだうめこ"],
  },
  {
    name: "中江兆民",
    image: "/images/famous/中江兆民.jpg",
    difficulty: "boss",
    aliases: ["なかえちょうみん"],
  },
  {
    name: "天草四郎時貞",
    image: "/images/famous/天草四郎時貞.jpg",
    difficulty: "normal",
    aliases: ["天草四郎","あまくさしろうときさだ","あまくさしろう"],
  },
  {
    name: "田中正造",
    image: "/images/famous/田中正造.jpg",
    difficulty: "normal",
    aliases: ["たなかしょうぞう"],
  },
  {
    name: "土方歳三",
    image: "/images/famous/土方歳三.jpg",
    difficulty: "normal",
    aliases: ["ひじかたとしぞう"],
  },
  {
    name: "東郷平八郎",
    image: "/images/famous/東郷平八郎.jpg",
    difficulty: "normal",
    aliases: ["とうごうへいはちろう"],
  },
  {
    name: "島崎藤村",
    image: "/images/famous/島崎藤村.jpg",
    difficulty: "boss",
    aliases: ["しまざきとうそん"],
  },
  {
    name: "湯川秀樹",
    image: "/images/famous/湯川秀樹.jpg",
    difficulty: "boss",
    aliases: ["ゆかわひでき"],
  },
  {
    name: "藤原道長",
    image: "/images/famous/藤原道長.jpg",
    difficulty: "normal",
    aliases: ["ふじわらのみちなが"],
  },
  {
    name: "徳川家光",
    image: "/images/famous/徳川家光.jpg",
    difficulty: "normal",
    aliases: ["とくがわいえみつ"],
  },
  {
    name: "徳川吉宗",
    image: "/images/famous/徳川吉宗.jpg",
    difficulty: "normal",
    aliases: ["とくがわよしむね"],
  },
  {
    name: "徳川綱吉",
    image: "/images/famous/徳川綱吉.jpg",
    difficulty: "normal",
    aliases: ["とくがわつなよし"],
  },
];
